{
 "title": "Flink Dashboard",
 "description": "Flink dashboard using the Prometheus exporter. https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/metrics.html#prometheus-orgapacheflinkmetricsprometheusprometheusreporter ",
 "tags": [ "flink" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JobManager Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TaskManager Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of TaskManagers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  },
  {
   "title": "Available taskslots",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs"
    }
   ]
  },
  {
   "title": "JobManager CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TaskManager CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time",
     "legendFormat": "{{instance}} Young Gen Time"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time",
     "legendFormat": "{{instance}} Old Gen Time"
    }
   ]
  },
  {
   "title": "JobManager Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_GarbageCollector_Copy_Time",
     "legendFormat": "{{instance}} GC Copy Time"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time",
     "legendFormat": "{{instance}} GC MarkSweep Time"
    }
   ]
  }
 ]
}